### ISSUE TITLE
Teams?

### ISSUE THREAD

**Issue by jprobotics** [JP-Robotics/redolent-octo-guacamole#2]
I wonder if we should have teams divided by hardware and software.  I think it should be JP ROBOTICS then RED TEAM / B:LUE TEAM then 2 repositories (hardware, software) under each TEAM.

**Comment by megaman-exe** [comment]
I don't think two separate repositories for each team will be necessary, since repositories only are useful for code.

My initial plan was to divide the teams into Red-Hardware and Red-Software, and Blue-Hardware and Blue-Software, or something similar.

That way, each team has their own repository and their own list of issues, and the people who won't actually be coding won't be able to edit the repository itself, only the issues, wiki, and website.

EDIT:
I left the teams as one of each because we don't know who will be on what team yet.  I can split the team into two later.

Does that make sense, or should we do it differently?

**Comment by jprobotics** [comment]
Repositories can actually hold any kind of documentation.

On Wed, Sep 2, 2015 at 7:40 AM, Benjamin Wilkinson <notifications@github.com

> wrote:
> 
> I don't think two separate repositories for each team will be necessary,
> since repositories only are useful for code.
> 
> My initial plan was to divide the teams into Red-Hardware and
> Red-Software, and Blue-Hardware and Blue-Software, or something similar.
> 
> That way, each team has their own repository and their own list of issues,
> and the people who won't actually be coding won't be able to edit the
> repository itself, only the issues, wiki, and website.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JP-Robotics/redolent-octo-guacamole/issues/2#issuecomment-137061379
> .

## 

It is change, continuing change, inevitable change, that is the dominant
factor in society today. No sensible decision can be made any longer
without taking into account not only the world as it is, but the world as
it will be.
Isaac Asimov
http://www.brainyquote.com/quotes/quotes/i/isaacasimo124394.html

**Comment by megaman-exe** [comment]
That's true...I just thought it might be more efficient to summarize the whole team under one repository.  Each repository can have a website linked to it, and since the robot is one project, I thought it would make the most sense to use the repository for the actual code, and then the website and wiki linked to the repository for other purposes.

We can try both methods before the kickoff event and see which works better.

**Comment by jprobotics** [comment]
You are the de facto leader, so I default to you and your vision.  Thank
you for having a vision.

On Wed, Sep 2, 2015 at 9:31 AM, Benjamin Wilkinson <notifications@github.com

> wrote:
> 
> That's true...I just thought it might be more efficient to summarize the
> whole team under one repository. Each repository can have a website linked
> to it, and since the robot is one project, I thought it would make the most
> sense to use the repository for the actual code, and then the website and
> wiki linked to the repository for other purposes.
> 
> We can try both methods before the kickoff event and see which works
> better.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JP-Robotics/redolent-octo-guacamole/issues/2#issuecomment-137103802
> .

## 

It is change, continuing change, inevitable change, that is the dominant
factor in society today. No sensible decision can be made any longer
without taking into account not only the world as it is, but the world as
it will be.
Isaac Asimov
http://www.brainyquote.com/quotes/quotes/i/isaacasimo124394.html

**Comment by megaman-exe** [comment]
I don't know about that, I have just thought about how things could fit together over the summer.  Please tell me if an idea I have isn't the best.

That goes for the rest of the team too, when you join github.
